version: '3.5'

services:

  nats:
    image: nats
    container_name: "nats"
    ports:
      - "4222:4222"
    healthcheck:
      test: [ "CMD", "nats", "ping" ]
      interval: 1s
      timeout: 1s
      retries: 5

  finance-service:
    build:
      context: finance-service-api
    container_name: "finance-service"
    ports:
      - "8081:8081"
    depends_on:
      mongo:
        condition: service_healthy
      nats:
        condition: service_started

  telegram-bot:
    build:
      context: telegram-bot-api
    container_name: "telegram-service"
    ports:
      - "8080:8080"
    depends_on:
      mongo:
        condition: service_healthy
      nats:
        condition: service_started

  mongo:
    image: mongo
    container_name: "mongodb"
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 1s
      timeout: 1s
      retries: 5

volumes:
  mongo-data:
