version: '3.5'

services:
  telegram-bot:
    build:
      dockerfile: Dockerfile
    container_name: "app"
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: "mongodb"
    ports:
      - "27070:27017"
