version: '3.5'

services:

  telegram-bot:
    build:
      dockerfile: Dockerfile
    container_name: "app"
    ports:
      - "8080:8080"
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo
    container_name: "mongodb"
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 1s
      timeout: 1s
      retries: 5

volumes:
  mongo-data:
