spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      uri: mongodb://localhost:27017/telegram-bank-bot-db
bot:
  token: #secret
  username: BankInfoBot

text:
  path: src/main/resources/texts/
  fileName: texts.properties

mono:
  url: https://api.monobank.ua/bank/currency




