spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      uri: mongodb://mongo:27017/telegram_bot_db

bot:
  token: #secret
  username: BankInfoBot

text:
  path: /texts/texts.properties

mono:
  url: https://api.monobank.ua/bank/currency
