spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      uri: mongodb://localhost:27017/telegram_bot_db

nats:
  url: nats://localhost:4222

server:
  port: 8082
