package com.ajaxproject.telegrambot.bot.enums

enum class TextPropertyName {

    WELCOME_TEXT,
    WRONG_NUMBER_TEXT,
    MENU_TEXT,
    CURRENCY_TEXT,
    FINANCE_MANAGE_TEXT,
    ADD_FINANCE_TEXT,
    SUCCESSFUL_ADD_FINANCE_TEXT,
    FAILED_ADD_FINANCE_TEXT,
    BACK_TO_MENU_TEXT,
    DATA_IS_DELETED_TEXT,
    NO_FINANCE_TEXT
}

enum class Buttons {

    GET_CURRENCY_USD_BUTTON,
    GET_CURRENCY_EUR_BUTTON,
    ADD_FINANCE_AGAIN_BUTTON,
    CURRENT_BALANCE_BUTTON,
    ADD_FINANCE_BUTTON,
    GET_ALL_INCOMES_BUTTON,
    GET_ALL_EXPENSES_BUTTON,
    GET_CURRENCY_RATE_BUTTON,
    MANAGE_FINANCES_MENU_BUTTON,
    GET_CURRENT_BALANCE_BUTTON,
    BACK_TO_MENU_BUTTON,
    DELETE_DATA_BUTTON
}
