package com.ajaxproject.telegrambot.bot.enums

enum class TextPropertyName {

    WELCOME_TEXT,
    WRONG_NUMBER_TEXT,
    MENU_TEXT,
    CURRENCY_TEXT,
    FINANCE_MANAGE_TEXT,
    ADD_FINANCE_TEXT,
    SUCCESSFUL_ADD_FINANCE,
    FAILED_ADD_FINANCE,
    BACK_TO_MENU
}

enum class Buttons {

    GET_CURRENCY_USD,
    GET_CURRENCY_EUR,
    ADD_FINANCE_AGAIN,
    CURRENT_BALANCE,
    ADD_FINANCE,
    GET_ALL_INCOMES,
    GET_ALL_EXPENSES,
    GET_CURRENCY_RATE,
    MANAGE_FINANCES_MENU,
    GET_CURRENCY_BALANCE,
    BACK_TO_MENU_BUTTON
}
