spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      uri: mongodb://localhost:27017/telegram_bot_db

bot:
  token: 6565348709:AAFReda6-Fl82NHP4TnVL-5QrPwUqgwrY4g
  username: BankInfoBot

text:
  path: /texts/texts.properties

mono:
  url: https://api.monobank.ua/bank/currency

nats:
  url: nats://localhost:4222
