spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      uri: mongodb://localhost:27017/telegram_bot_db

bot:
  token: #secret
  username: FinanceManageBot

mono:
  url: https://api.monobank.ua/bank/currency

nats:
  url: nats://localhost:4222
