spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:

    mongodb:
      uri: mongodb://localhost:27017/telegram_bot_db

    redis:
      port: 6379
      host: localhost

  kafka:
    bootstrap-servers: http://localhost:9092
    properties:
      schema:
        registry:
          url: http://localhost:8081

bot:
  token: #secret
  username: FinanceManageBot

mono:
  url: https://api.monobank.ua/bank/currency

nats:
  url: nats://localhost:4222

redis-properties:
  ttl-minutes: 5
  prefix-key: currency-key-

grpc:
  server:
    port: 9091
    security:
      enabled: false
